### ISSUE TITLE
imageSearchC -- documentation request

### ISSUE THREAD

**Issue by Kenji-03** [Masonjar13/AHK-Library#3]
I just added your library (and your Gdip_ALL.ahk) due to the default AHK image search not really working for me: I'd like to request more clarification in the documentation.

"vari"": ex. is it 0-100 or 0-1?
"trans: is it hex code for the colors or 0-255 RGB? what is the order to list them in?

being a bit more verbose in the commented section would be greatly appreciated.

**Comment by Masonjar13** [comment]
I didn't add it due to it being 1:1 with the [original documentation for ImageSearch](https://www.autohotkey.com/docs/commands/ImageSearch.htm#ImageFile). The only difference is I've put them as parameters, rather than options before the image file path. It wouldn't hurt to add a little bit of information on them, though.

**Comment by Masonjar13** [comment]
https://github.com/Masonjar13/AHK-Library/commit/833fbba7e120475730ad1953672486174d2e2772

**Comment by Kenji-03** [comment]
Thank you for taking the time to clarify, I appreciate you sharing your
code and fulfilling my noob request
